In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('heart.csv')
df.head(3)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0

In [3]:
from scipy import stats

In [4]:
df.shape

(918, 12)

In [5]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [6]:
df[df.Cholesterol>(df.Cholesterol.mean()+3*df.Cholesterol.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
76    32   M           ASY        118          529          0     Normal   
149   54   M           ASY        130          603          1     Normal   
616   67   F           NAP        115          564          0        LVH   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
76     130              N      0.0     Flat             1  
149    125              Y      1.0     Flat             1  
616    160              N      1.6     Flat             0

In [7]:
numeric_df = df.select_dtypes(include=[np.number])
numeric_df

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease
0     40        140          289          0    172      0.0             0
1     49        160          180          0    156      1.0             1
2     37        130          283          0     98      0.0             0
3     48        138          214          0    108      1.5             1
4     54        150          195          0    122      0.0             0
..   ...        ...          ...        ...    ...      ...           ...
913   45        110          264          0    132      1.2             1
914   68        144          193          1    141      3.4             1
915   57        130          131          0    115      1.2             1
916   57        130          236          0    174      0.0             1
917   38        138          175          0    173      0.0             0

[918 rows x 7 columns]

In [8]:
z_scores = np.abs(stats.zscore(numeric_df))
print(z_scores)

[[1.4331398  0.41090889 0.82507026 ... 1.38292822 0.83243239 1.11311472]
 [0.47848359 1.49175234 0.17196105 ... 0.75415714 0.10566353 0.89837999]
 [1.75135854 0.12951283 0.7701878  ... 1.52513802 0.83243239 1.11311472]
 ...
 [0.37009972 0.12951283 0.62016778 ... 0.85706875 0.29328271 0.89837999]
 [0.37009972 0.12951283 0.34027522 ... 1.4615246  0.83243239 0.89837999]
 [1.64528563 0.30282455 0.21769643 ... 1.42222641 0.83243239 1.11311472]]


In [9]:
df_no_outliers = df[(z_scores < 3).all(axis=1)]
df_no_outliers.head(3)
df_no_outliers.shape

(899, 12)

In [10]:
df['Sex'].unique()

array(['M', 'F'], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
label_encoder = LabelEncoder()
for col in ["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"]:
    df[col] = label_encoder.fit_transform(df[col])

In [13]:
df

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               0      0.0         2             0  
1      156               0      1.0         1             1  
2       98               0      0.0         2             0  
3      108               1      1.5         1             1  
4      122               0      0.0         2             0  
..     ...             ...      ...       ...           ...  
913    132               0      1.2         1             1  
914    141               0      3.4         1             1  
915    115               1      1.2         1             1  
916    174               0      0.0         1             1  
917    173               0      0.0         2             0  

[918 rows x 12 columns]

In [14]:
X = df.drop('HeartDisease',axis=1)
X

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
0      172               0      0.0         2  
1      156               0      1.0         1  
2       98               0      0.0         2  
3      108               1      1.5         1  
4      122               0      0.0         2  
..     ...             ...      ...       ...  
913    132               0      1.2         1  
914    141               0      3.4         1  
915    115               1      1.2         1  
916    174               0      0.0         1  
917    173               0      0.0         2  

[918 rows x 11 columns]

In [15]:
y = df['HeartDisease']
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,y, test_size=0.2)

In [17]:
xtrain.shape

(734, 11)

In [18]:
from  sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()

In [19]:
logmodel.fit(xtrain,ytrain)

C:\Users\91982\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
logmodel.score(xtest,ytest)

0.8858695652173914

In [21]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
Xscaled = scaler.fit_transform(X)

In [22]:
from sklearn.svm import SVC
svcmodel = SVC()


In [23]:
svcmodel.fit(xtrain,ytrain)

SVC()

In [24]:
svcmodel.score(xtest,ytest)

0.7228260869565217

In [25]:
from sklearn.ensemble import RandomForestClassifier
rfmodel = RandomForestClassifier(n_estimators=80,random_state=30)


In [26]:
rfmodel.fit(xtrain,ytrain)

RandomForestClassifier(n_estimators=80, random_state=30)

In [27]:
rfmodel.score(xtest,ytest)

0.875

In [29]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
Xscaled = scaler.fit_transform(xtrain)

In [30]:
rfmodel.fit(Xscaled,ytrain)

RandomForestClassifier(n_estimators=80, random_state=30)

In [31]:
rfmodel.score(xtest,ytest)

C:\Users\91982\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


0.6413043478260869

In [39]:
from sklearn.decomposition import PCA
pcamodel = PCA(0.95)

In [45]:
x_pca = pcamodel.fit_transform(X)

In [46]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(x_pca, y, test_size=0.2, random_state=30)

In [41]:
rfmodel.fit(x_pca,ytrain)

RandomForestClassifier(n_estimators=80, random_state=30)

In [47]:
pcamodel.explained_variance_ratio_

array([0.92021836, 0.04913303])

In [48]:
rfmodel.score(X_test_pca,y_test)

0.8043478260869565